services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    init: true
    environment:
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
    volumes:
      - type: bind
        source: "."
        target: /workspace
      - type: bind
        source: /mnt/wslg
        target: /mnt/wslg
